#include "version.h"
#include <time.h>
#include "char.h"
#include "object.h"
#include "lssproto_serv.h"
#include "npcutil.h"
#include "handletime.h"
#include <string.h>
#include "char_base.h"
#include "configfile.h"
#include "npc_bigsmallpet.h"
